import { mkdir, readFile, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"

export type InstallScope = "project" | "global" | "custom"

export interface InstallOptions {
  readonly cwd?: string
  readonly global?: boolean
  readonly configDir?: string
  readonly force?: boolean
  readonly packageEntryUrl?: string
  readonly pluginName?: string
}

export interface InstallResult {
  readonly scope: InstallScope
  readonly configDir: string
  readonly pluginDir: string
  readonly pluginFile: string
  readonly packageEntryUrl: string
  readonly changed: boolean
}

const DEFAULT_PLUGIN_NAME = "opencode-cloakpipe"

export async function installLocalPlugin(options: InstallOptions = {}): Promise<InstallResult> {
  const cwd = path.resolve(options.cwd ?? process.cwd())
  const pluginName = options.pluginName ?? DEFAULT_PLUGIN_NAME
  const { scope, configDir } = resolveConfigDir(cwd, options)
  const pluginDir = path.join(configDir, "plugins")
  const pluginFile = path.join(pluginDir, `${pluginName}.js`)
  const packageEntryUrl = options.packageEntryUrl ?? currentPackageEntryUrl()
  const content = renderPluginShim(packageEntryUrl)
  const existing = await readTextIfExists(pluginFile)

  if (existing === content) {
    return { scope, configDir, pluginDir, pluginFile, packageEntryUrl, changed: false }
  }

  if (existing !== undefined && !options.force) {
    throw new Error(`${pluginFile} already exists. Re-run with --force to replace it.`)
  }

  await mkdir(pluginDir, { recursive: true })
  await writeFile(pluginFile, content, "utf8")
  return { scope, configDir, pluginDir, pluginFile, packageEntryUrl, changed: true }
}

export function resolveConfigDir(cwd: string, options: Pick<InstallOptions, "global" | "configDir">): {
  scope: InstallScope
  configDir: string
} {
  if (options.configDir) {
    return { scope: "custom", configDir: path.resolve(cwd, options.configDir) }
  }
  if (options.global) {
    return { scope: "global", configDir: path.join(os.homedir(), ".config", "opencode") }
  }
  return { scope: "project", configDir: path.join(cwd, ".opencode") }
}

export function renderPluginShim(packageEntryUrl: string): string {
  return `// Generated by opencode-cloakpipe.\n// Re-run \`opencode-cloakpipe install\` after moving or rebuilding this package.\nexport { default, OpencodeCloakPipe } from ${JSON.stringify(packageEntryUrl)}\n`
}

function currentPackageEntryUrl(): string {
  const distDir = path.dirname(fileURLToPath(import.meta.url))
  return pathToFileURL(path.join(distDir, "index.js")).href
}

async function readTextIfExists(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, "utf8")
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return undefined
    throw error
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error
}
